site_name: Личный блог о всяком

nav:
  - О чем это все: index.md
  - Впечатления о книгах:
    - reviews/lukyanenko_porog_1.md
    - reviews/sworm.md
    - reviews/plotnikov_enemy.md
    - stoev_za_poslednim_porogom.md
theme:
  name: material

plugins:
  - search